version: '3.8'
services:
  Wildzone-suppliers-database:
    image: mysql
    networks:
      - Wildzone-network
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      
networks:
  Wildzone-network:     